import Providers from '@/utils/Provider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import store from '@/store/store'
import { ProvidersWithStore } from '@/store/Providers'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ProvidersWithStore>
      <html lang="en">
      <body className={inter.className}>
       
        <Providers>
          {children}
        </Providers>
       
      </body>
    </html>
    </ProvidersWithStore>
      
    
  )
}
